### ISSUE TITLE
Quick Check-In & Check-Out

### ISSUE THREAD

**Issue by bastianrickmann** [ChristophBe/desks#14]
URL that allows room booking for the current moment until standard end time and an the same url would can “logout” the same day that edits the end time of the current booking the actual leaving time.

**Comment by ChristophBe** [comment]
This is not really a use-case for this System. The goals is to plan the availability of desks not to track who was at the office. A more use full feature would be to have a view to quickly see if there is free desks in the office. In the case that some one wants to go to the office spontaneously.

**Comment by bastianrickmann** [comment]
The point of it would not be to track who is in the office but to easily add yourself into the room in case you forgot and be transparent to all others who spontaneously decide to go to the office.

**Comment by bastianrickmann** [comment]
" an the same url would can ‚logout' the same day that edits the end time of the current booking the actual leaving time.“ wasn’t intended for spontaneously leaving and correcting the availabilty of the room.
